package com.sei.nexus.governance;

import java.util.ArrayList;
import java.util.List;

/**
 * Mutable builder that accumulates governance decisions for a single query step.
 * Passed through the governance chain and handed to {@link GovernanceAuditService}
 * at the end of execution.
 */
public final class AuditContext {

    private String       userEmail;
    private String       userRole;
    private String       runKey;
    private String       connectionKey;
    private List<String> objectKeys         = new ArrayList<>();
    private List<String> columnsAccessed    = new ArrayList<>();
    private List<String> columnsMasked      = new ArrayList<>();
    private List<String> rlsPoliciesApplied = new ArrayList<>();
    private List<String> contractsChecked   = new ArrayList<>();
    private List<String> contractsViolated  = new ArrayList<>();
    private String       originalSql;
    private String       executedSql;
    private Integer      rowCountReturned;
    private Integer      rowsFilteredByRls;
    private Integer      executionMs;
    private String       ipAddress;

    private AuditContext() {}

    public static AuditContext of(String userEmail, String userRole,
                                  String runKey, String connectionKey) {
        AuditContext ctx = new AuditContext();
        ctx.userEmail      = userEmail;
        ctx.userRole       = userRole;
        ctx.runKey         = runKey;
        ctx.connectionKey  = connectionKey;
        return ctx;
    }

    public AuditContext originalSql(String sql)          { this.originalSql        = sql;   return this; }
    public AuditContext executedSql(String sql)           { this.executedSql         = sql;   return this; }
    public AuditContext rowCount(int count)               { this.rowCountReturned    = count; return this; }
    public AuditContext rowsFilteredByRls(int count)     { this.rowsFilteredByRls  = count; return this; }
    public AuditContext executionMs(int ms)               { this.executionMs         = ms;    return this; }
    public AuditContext ipAddress(String ip)             { this.ipAddress           = ip;    return this; }

    public AuditContext addObjectKeys(List<String> keys) {
        if (keys != null) objectKeys.addAll(keys);
        return this;
    }

    public AuditContext addColumnsAccessed(List<String> cols) {
        if (cols != null) columnsAccessed.addAll(cols);
        return this;
    }

    public AuditContext applyMaskResult(MaskResult r) {
        columnsMasked.addAll(r.maskedColumns());
        return this;
    }

    public AuditContext applyRlsResult(RlsResult r) {
        rlsPoliciesApplied.addAll(r.policiesApplied());
        return this;
    }

    public AuditContext applyContractResult(ContractResult r) {
        contractsChecked.addAll(r.contractsChecked());
        contractsViolated.addAll(r.contractsViolated());
        return this;
    }

    /** Derives the event type from the governance decisions accumulated so far. */
    public String deriveEventType(boolean blocked) {
        if (blocked)                            return "ACCESS_DENIED";
        if (!contractsViolated.isEmpty())       return "CONTRACT_VIOLATED";
        if (!columnsMasked.isEmpty()
         && !rlsPoliciesApplied.isEmpty())      return "COLUMN_MASKED";
        if (!columnsMasked.isEmpty())           return "COLUMN_MASKED";
        if (!rlsPoliciesApplied.isEmpty())      return "RLS_APPLIED";
        return "QUERY_EXECUTED";
    }

    public AuditEvent toEvent(String eventType) {
        return new AuditEvent(
                null, // key generated by repository
                eventType,
                userEmail, userRole, runKey, connectionKey,
                objectKeys.toArray(new String[0]),
                columnsAccessed.toArray(new String[0]),
                columnsMasked.toArray(new String[0]),
                rlsPoliciesApplied.toArray(new String[0]),
                contractsChecked.toArray(new String[0]),
                contractsViolated.toArray(new String[0]),
                originalSql, executedSql,
                rowCountReturned, rowsFilteredByRls, executionMs, ipAddress,
                null);
    }
}
